config/next_seo.js
Definitely a well-designed website!
=> fix(home-page): fix a typo in website's description

src/containers/Sidebar/store.js, src/pages/_error.js, src/pages/communities/index.js, src/pages/communities/new.js, src/pages/community.js, src/pages/cool-guide.js, src/pages/editor.js, src/pages/have-a-drink.js, src/pages/home/posts.js, src/pages/index.js, src/pages/interview.js, src/pages/job.js, src/pages/meetups.js, src/pages/oauth.js, src/pages/post.js, src/pages/recipes.js, src/pages/repo.js, src/pages/sponsor.js, src/pages/trending.js, src/pages/user.js, src/pages/video.js, src/pages/works.js, src/stores/RootStore/index.js, src/stores/RootStore/test/index.test.js, src/stores/init.js
- include langs and actions around it
- remove langs when init store per page
=> chore(i18n): clean up lang-related keys in root store

src/components/MarkdownEditor/exportContent.js, src/components/StatusBox/index.js, src/containers/JoinModal/service.js, src/containers/Preview/styles/index.js, src/containers/thread/RoadmapThread/service.js, src/containers/viewer/VideoViewer/logic.js, src/hooks/useResize.js, src/pages/communities/index.js, src/pages/communities/new.js, src/pages/community.js, src/pages/cool-guide.js, src/pages/have-a-drink.js, src/pages/home/posts.js, src/pages/index.js, src/pages/interview.js, src/pages/job.js, src/pages/meetups.js, src/pages/post.js, src/pages/recipes.js, src/pages/repo.js, src/pages/sponsor.js, src/pages/trending.js, src/pages/user.js, src/pages/video.js, src/pages/works.js, utils/bstore.js, utils/scripts/checkmark.js, utils/scripts/component_exists.js, utils/scripts/generators/container/service.js.hbs
turn async function like:
```js
export async function getServerSideProps(props) {}
```
into es6 style
```js
export const getServerSideProps = async props {}
```
=> chore(functions): use es6 style aync function styles

src/containers/Sidebar/styles/index.js
=> fix(sidebar): wrong position fixed when wide screen

src/components/CommunityStatesPad/index.js, src/components/PostItem/styles/index.js, src/containers/Header/styles/header.js, src/containers/banner/CommunityBanner/DigestView.js, src/containers/banner/CommunityBanner/styles/digest_view.js, src/containers/content/CommunityContent/styles/index.js, utils/common_styles.js
now home community's banner is smaller than the standard community banner, by remove the links and founding option
=> Home layout

cypress/integration/home/layout.spec.js, package.docker.json, package.json, src/containers/Doraemon/InputEditor.js, src/containers/Doraemon/index.js, src/containers/Doraemon/logic/index.js, src/containers/Doraemon/store.js, src/containers/Doraemon/styles/index.js, src/containers/Doraemon/styles/input_editor.js, src/containers/ErrorBox/index.js, src/containers/GlobalLayout/index.js, src/containers/Header/FixedHeader.js, src/containers/Header/UserAccount.js, src/containers/Header/styles/user_account.js, src/containers/Preview/index.js, src/containers/content/HaveADrinkContent/index.js, src/hooks/useShortcut.js, yarn.lock
1. use [tinykeys](https://github.com/jamiebuilds/tinykeys) for more small size
2. add basic test for Doramon Comp
=> use tinykeys as shortcut lib

src/containers/GlobalLayout/dynamic.js, src/containers/GlobalLayout/index.js, src/containers/Preview/DynamicComps.js, src/containers/Preview/Viewer.js, src/containers/Preview/index.js, src/containers/editor/PostEditor/index.js, src/containers/viewer/JobViewer/index.js, src/containers/viewer/PostViewer/index.js, src/containers/viewer/RepoViewer/index.js
1. use new dynamic import style 
**old**
```jsx
export const DynamicAccountViewer = dynamic({
loader:  () => import('@/containers/viewer/AccountViewer')
loading: ....
})
```
**new**: 
```jsx
export const DynamicAccountViewer = dynamic(
() => import('@/containers/viewer/AccountViewer'),
commonConfig,
)
```
2. in some component <> will cause error
should revert to old <React.Fragment> style
=> fix(Preview): new dynamic style && fix React.Fragment style error

src/components/Buttons/ArrowButton.js, src/components/Buttons/styles/arrow_button.js, src/containers/content/CreateCommunityContent/Banner/SetupDomain/index.js, src/containers/content/CreateCommunityContent/Banner/SetupInfo/index.js
transparentFirst is confused, dim when idle is more readable
=> refactor(Naming): transparentFirst -> dimWhenIdle

src/components/Navigator/styles/more_panel/index.js, src/components/Switcher/Tabs/TabItem.js, src/components/Switcher/Tabs/index.js, src/components/Switcher/styles/metric/tabs.js, src/components/Switcher/styles/tabs/tab_item.js, src/components/ThemeSelector/style/gallery_selector.js, src/containers/Preview/AddOn.js, src/containers/Preview/MobileCloser.js, src/containers/Preview/SliderPreview.js, src/containers/Preview/styles/add_on.js, src/containers/Preview/styles/index.js, src/containers/Preview/styles/mobile_closer.js, src/containers/Preview/styles/viewer.js
=> Mobile previewer

src/containers/Drawer/Viewer.js, src/containers/Drawer/styles/index.js, src/containers/Drawer/styles/metrics.js
=> Fix drawer animation

src/components/ArticleItemPrefixLabel/styles/index.js, src/components/CommunityStatesPad/index.js, src/components/CommunityStatesPad/styles/index.js, src/components/CommunityStatesPad/styles/number_group.js, src/components/InlineTags/styles/index.js, src/components/Navigator/styles/index.js, src/components/Navigator/styles/main_entries.js, src/components/PostItem/DigestView/DesktopView.js, src/components/PostItem/DigestView/MobileView.js, src/components/PostItem/DigestView/index.js, src/components/PostItem/index.js, src/components/PostItem/styles/mobile_view.js, src/containers/Header/styles/fixed_header.js, src/containers/banner/CommunityBanner/ExpandTexts.js, src/containers/banner/CommunityBanner/styles/digest_view/column_view/index.js, src/containers/banner/CommunityBanner/styles/expand_texts.js, src/containers/banner/CommunityBanner/styles/index.js, src/containers/content/CommunityContent/styles/index.js, src/containers/thread/PostsThread/styles/index.js
=> Community mobile view

src/containers/C11NSettingPanel/GeneralSettings.js, src/containers/GlobalLayout/index.js, src/containers/GlobalLayout/styles/index.js, src/containers/banner/CommunityBanner/DigestView/ColumnView/index.js, src/containers/banner/CommunityBanner/DigestView/index.js, src/containers/banner/CommunityBanner/styles/digest_view/column_view/index.js, src/containers/banner/CommunityBanner/styles/digest_view/index2.js, src/containers/content/CommunityContent/index.js, src/containers/content/CommunityContent/styles/index.js
todo: remove c11n community row layout on mobile, both panel and account page
=> refactor(CommunityBanner): reduce min-height on mobile

src/components/CustomScroller/VerticalScroller.js, src/hooks/useCustomScroll.js, utils/themes/index.js, utils/themes/skins/cyan.js, utils/themes/skins/github.js, utils/themes/skins/green.js, utils/themes/skins/iron_green.js, utils/themes/skins/monokai.js, utils/themes/skins/purple.js, utils/themes/skins/solarized_dark.js, utils/themes/skins/yellow.js
=> refactor(CustomScrollBar): scrollbar className based on theme meta data

src/components/Buttons/Button.js, src/components/Buttons/styles/button.js, src/components/Buttons/styles/metircs/button.js, src/components/EmailSubscriber/DefaultLayout/ActiveView.js
=> refactor(button): add disable style for primary type

src/components/Switcher/Tabs/CardView.js, src/components/Switcher/Tabs/DesktopView.js, src/components/Switcher/Tabs/MobileView.js, src/components/Switcher/Tabs/MobileView/ExpandView.js, src/components/Switcher/Tabs/MobileView/NormalView.js, src/components/Switcher/Tabs/MobileView/index.js, src/components/Switcher/Tabs/TabItem.js, src/components/Switcher/Tabs/index.js, src/components/Switcher/styles/metric/tabs.js, src/components/Switcher/styles/tabs/index.js, src/components/Switcher/styles/tabs/mobile.js, src/components/Switcher/styles/tabs/mobile_view/expand_view.js, src/components/Switcher/styles/tabs/mobile_view/normal_view.js, src/components/Switcher/styles/tabs/tab_icon.js, src/components/Switcher/styles/tabs/tab_item.js, src/components/TabBar/NormalView.js, src/components/TabBar/index.js, src/containers/GlobalLayout/index.js, src/containers/GlobalLayout/logic.js, src/containers/GlobalLayout/styles/index.js, src/containers/Header/styles/header.js, src/containers/banner/CommunityBanner/DigestView/ColumnView/index.js, src/containers/banner/CommunityBanner/styles/digest_view/column_view/index.js
=> tabs enhance for mobile

src/containers/content/MeetupsContent/Card/Date.js, src/containers/content/MeetupsContent/Card/TextCard.js, src/containers/content/MeetupsContent/Card/TextWithImgCard.js, src/containers/content/MeetupsContent/Card/index.js, src/containers/content/MeetupsContent/store.js, src/containers/content/MeetupsContent/styles/card/date.js, src/containers/content/MeetupsContent/styles/card/text_card.js, src/containers/content/MeetupsContent/styles/card/text_with_img_card.js
=> style(meetup-card): adjust date style && re-org codebase

package.docker.json, package.json, src/containers/tool/Drawer/MobileCloser.js, src/containers/tool/Drawer/Viewer.js, src/containers/tool/Drawer/index.js, src/containers/tool/Drawer/store.js, src/containers/tool/Drawer/styles/index.js, src/containers/tool/Drawer/styles/metrics.js, yarn.lock
=> drawer swipe action

src/containers/unit/ModeLine/BottomBar/ArrowBlock.js, src/containers/unit/ModeLine/BottomBar/CommunityInfo.js, src/containers/unit/ModeLine/styles/bottom_bar/arrow_block.js, src/containers/unit/ModeLine/styles/bottom_bar/community_info.js
=> Modeline subscribe mode

src/components/ContentBanner/styles/index.js, src/components/DiscussLinker/styles/index.js, src/components/FeedsBar/styles/source_selector.js, src/components/GalleryHub/styles/fame_people_gallery.js, src/components/JobItem/styles/company_info.js, src/components/JobItem/styles/job_info.js, src/components/LoadingEffects/styles/community_holder.js, src/components/Navigator/styles/brief_view.js, src/components/PostItem/styles/digest_view/body.js, src/components/PostItem/styles/list_view.js, src/components/RepoItem/styles/footer.js, src/components/RepoItem/styles/header.js, src/components/UserCell/styles/index.js, src/components/VideoItem/styles/index.js, src/containers/content/WorksContent/styles/banner/recommendation.js, src/containers/content/WorksContent/styles/list/card.js, src/containers/digest/CommunityDigest/styles/expand_texts.js, src/containers/layout/ThemePalette/GlobalStyle.js, src/containers/tool/CommunitySetter/styles/community.js, src/containers/tool/Doraemon/styles/results_list.js, src/containers/tool/MailBox/styles/mention_list.js, src/containers/unit/Comments/Comment/styles/base.js, src/containers/unit/Comments/styles/index.js, src/containers/unit/ModeLine/styles/bottom_bar/community_info.js, src/containers/unit/Sidebar/styles/menu_bar.js, src/containers/user/UserLister/styles/user_list.js, src/containers/viewer/MailsViewer/styles/mention_list.js, utils/common_styles.js
truncate is hard to remember and cutFrom is the same world in utils functions
=> refactor(naming): truncate -> cutFrom in common_styles

src/containers/layout/GlobalLayout/index.js, src/containers/unit/ModeLine/BottomBar/index.js, utils/functions.js, utils/index.js
by default click && double click is conflict with each other
see tricky part in https://github.com/facebook/react/issues/3185#issuecomment-75138124
=> Dbclick to top on Modeline

src/components/DivideText/index.js, src/components/DivideText/styles/index.js, src/components/DivideText/tests/index.test.js, src/containers/content/CommunityContent/styles/index.js, src/containers/tool/Drawer/store.js, src/containers/unit/ModeLine/BottomBar/index.js, src/containers/unit/ModeLine/logic.js, src/containers/unit/ModeLine/store.js, src/containers/unit/ModeLine/styles/bottom_bar/arrow_block.js, src/containers/unit/ModeLineMenu/SearchMenu.js, src/containers/unit/ModeLineMenu/index.js, src/containers/unit/ModeLineMenu/styles/search_menu.js, utils/constant/type.js
=> [ModelineMenu] add search menu demo

src/components/PagedContents/styles/community_recommends.js, src/components/Pagi/Next/Bottom.js, src/components/Pagi/Next/Center.js, src/components/Pagi/Perv/Bottom.js, src/components/Pagi/Perv/Center.js, src/components/Pagi/styles/index.js, src/components/Pagi/styles/next/bottom.js, src/components/Pagi/styles/next/center.js, src/components/Pagi/styles/perv/bottom.js, src/components/Pagi/styles/perv/center.js
=> style(Pagi): adjust styles on mobile

src/components/Switcher/styles/tabs/mobile_view/normal_view.js
=> style(tabs): adjust MoreWrapper on mobile

package.docker.json, package.json, src/components/AvatarFallback/index.js, src/components/AvatarFallback/styles/index.js, src/components/AvatarFallback/styles/metric.js, src/components/AvatarsRow/index.js, src/components/AvatarsRow/styles/index.js, src/components/AvatarsRow/styles/metric.js, src/components/Img/LazyLoadImg.js, src/components/Img/index.js, src/components/PostItem/DigestView/DesktopView/index.js, src/components/PostItem/styles/digest_view/index.js, src/components/Tooltip/index.js, src/components/Tooltip/styles/index.js, src/containers/digest/ArticleDigest/MobileView/StateInfo.js, src/containers/unit/ArticleFooter/AuthorInfo/index.js, src/containers/unit/Comments/Comment/Header.js, src/containers/unit/ModeLine/TopBar/MobileView/ArticleBar/index.js, utils/css.js, utils/themes/skins/solarized_dark.js, yarn.lock
nextjs 10 's new Image component it not work as expect, use [react-lazy-load-image-component](https://www.npmjs.com/package/react-lazy-load-image-component) instead
=> refactor(Image): lazy load

src/components/Img/LazyLoadImg.js, src/components/Img/index.js, src/containers/layout/ThemePalette/ThirdPartyOverWrite.js, src/containers/layout/ThemePalette/index.js
default blur effect is too big, change it to 3px looks nice
=> refactor(lazy-image): adjust blur effect

src/components/EmailSubscriber/styles/simple_layout.js, src/components/PostItem/DigestView/DesktopView/Body.js, src/components/PostItem/styles/digest_view/body.js, src/containers/unit/Footer/DesktopView/DigestView/index.js
=> refactor(PostItem): add preview hint && adjust extra info

src/components/AvatarFallback/index.js, src/components/AvatarFallback/styles/index.js, src/components/AvatarFallback/styles/metric.js, src/containers/digest/CommunityDigest/styles/digest_view/column_view/index.js, src/containers/unit/Header/logic.js, src/containers/unit/Header/store.js
=> refactor(Avatar): placeholder letter count based on width

src/components/Switcher/Radio.js, src/components/Switcher/Tabs/DrawerView.js, src/components/Switcher/Tabs/index.js, src/components/Switcher/styles/metric/radio.js, src/components/Switcher/styles/radio.js, src/components/Switcher/styles/tabs/drawer_view.js, src/components/ThemeSelector/GallerySelector.js, src/components/ThemeSelector/style/gallery_selector.js, src/containers/tool/C11NSettingPanel/GeneralSettings.js, src/containers/tool/C11NSettingPanel/index.js, src/containers/tool/C11NSettingPanel/styles/gerneral_settings.js, src/containers/tool/C11NSettingPanel/styles/index.js, src/containers/tool/C11NSettingPanel/styles/theme_settings.js, utils/constant/view.js
=> refactor(C11NPanel): Redesign 

src/components/GalleryHub/FriendsGallery.js, src/components/GalleryHub/styles/friends_gallery.js, src/containers/content/FriendsContent/index.js, src/containers/content/FriendsContent/styles/index.js, src/containers/layout/GlobalLayout/index.js, utils/width.js
=> refactor(Friends): new UI/UX

src/containers/content/WorksContent/List/BestTab.js, src/containers/content/WorksContent/styles/list/best_tab.js
=> style(works): adjust BestTab style

src/containers/layout/GlobalLayout/styles/index.js
=> refactor(GlobalLayout): opacity for backgroumd space image

src/containers/content/PostContent/styles/desktop_view.js, src/containers/digest/ArticleDigest/styles/desktop_view/index.js, src/containers/tool/ArticleSticker/styles/left_sticker/index.js, src/containers/unit/Header/styles/desktop_view/article_view.js, utils/width.js
=> fix(article-page): fix choas in desktopL screen

cypress/integration/404/community.spec.js, cypress/integration/404/user.spec.js, cypress/integration/home/layout.spec.js, src/components/ErrorPage/CodeSnippets.js, src/components/ErrorPage/ErrorDesc.js, src/components/ErrorPage/NotFoundMessage.js, src/components/ErrorPage/SpinPlanet.js, src/components/ErrorPage/index.js, src/components/ErrorPage/styles/code_snippets.js, src/components/ErrorPage/styles/index.js, src/components/ErrorPage/styles/spin_planet.js, src/pages/user.js, utils/errors/index.js
=> refactor(404): redesign

src/components/Buttons/styles/publish_button.js, src/containers/content/CommunityContent/styles/index.js, src/containers/thread/PostsThread/styles/index.js
=> refactor(post-thread): redesign layout

package.json, src/components/Select/components.js, src/components/Select/index.js, src/components/Select/styles/index.js, src/components/Select/styles/metric.js, src/components/Select/tests/index.test.js, src/containers/editor/WorksEditor/Content/BasicInfoPart/index.js, src/containers/editor/WorksEditor/store.js, src/containers/editor/WorksEditor/styles/content/basic_info_part/index.js, yarn.lock
=> feat(select): react-select play around

cypress/integration/discovery/layout.spec.js, src/components/Navigator/styles/main_entries.js
=> style(header): navi-links rm bottom border on hover

src/containers/content/WorksContent/RightSidebar/InterviewsList.js, src/containers/content/WorksContent/RightSidebar/index.js, src/containers/content/WorksContent/styles/right_sidebar/index.js, src/containers/content/WorksContent/styles/right_sidebar/interviews_list.js
=> chore(works): analysis concept && style adjust

src/components/TheAvatar/PostItemAvatar.js, src/components/TheAvatar/styles/post_item_avatar.js, src/components/UserBrief/styles/avatar.js, src/components/UserBrief/styles/index.js, src/containers/content/UserContent/styles/index.js
=> style(avatar): quote image concept
